//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System.Data.SQLite;
//using SQLite-net;
using System;
using System.Data;
using System.ComponentModel.DataAnnotations;

namespace Weatherforecast
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                //db.CreateTable<weatherforecast>();
                /*var record = new weatherforecast
                {
                    forecastdate = "2018-06-24",
                    tempc = 32,
                    tempf = 89,
                    summary = "Scorching"
                };
                db.Insert(record);
                db.Dispose(); */
            }
        }
    }
    public partial class weatherforecast
    {
        //[PrimaryKey, AutoIncrement]
        [Key]
        public Int64 id { get; set; }
        
        public DateTime? forecastdate { get; set; }
        
        public Decimal? tempc { get; set; }
        
        public Decimal? tempf { get; set; }
        
        [MaxLength(255)]
        public String summary { get; set; }
        
    }
    
}
